export const MOCK_STATUS = {
  bot_online: true,
  db_connected: true,
  last_heartbeat: "2026-01-15T10:20:30Z",
  queue_depth: 0,
  active_guilds: 1,
};

export const MOCK_REPORTS = [
  {
    id: 1024,
    reporter_name: "GM Stone",
    reported_user_name: "Stone助手",
    report_reason: "这是杀猪盘",
    llm_decision: "INVALID_REPORT",
    llm_confidence: 0.12,
    llm_reasoning: "未发现明显诈骗或广告特征。",
    reported_message_content: "想一起打本吗？我这边有队。",
    reported_message_url: "https://discord.com/channels/123/456/789",
    reported_user_history: JSON.stringify([
      { created_at: "2026-01-15T09:40:10Z", content: "今晚有空吗？" },
      { created_at: "2026-01-15T09:45:20Z", content: "拉你进群一起玩。" },
    ]),
    action_taken: "NONE",
    status: "DONE",
    created_at: "2026-01-15T09:58:12Z",
  },
  {
    id: 1023,
    reporter_name: "玩家A",
    reported_user_name: "陌生人X",
    report_reason: "疑似广告",
    llm_decision: "BAN",
    llm_confidence: 0.91,
    llm_reasoning: "包含外链、引导私信和高风险关键词。",
    reported_message_content: "加我微信领福利 http://example.com",
    reported_message_url: "https://discord.com/channels/123/456/790",
    reported_user_history: JSON.stringify([
      { created_at: "2026-01-15T09:12:10Z", content: "免费福利看这里" },
      { created_at: "2026-01-15T09:18:46Z", content: "进群加我领取" },
    ]),
    action_taken: "BAN",
    status: "DONE",
    created_at: "2026-01-15T09:40:48Z",
  },
  {
    id: 1022,
    reporter_name: "玩家B",
    reported_user_name: "新账号",
    report_reason: "不确定",
    llm_decision: "NEED_GM",
    llm_confidence: 0.52,
    llm_reasoning: "内容中有疑似交易但语义不明确。",
    reported_message_content: "有资源的来聊聊",
    reported_message_url: "https://discord.com/channels/123/456/791",
    reported_user_history: JSON.stringify([
      { created_at: "2026-01-15T08:55:10Z", content: "新人报到" },
      { created_at: "2026-01-15T09:01:42Z", content: "有资源的加我" },
    ]),
    action_taken: "ESCALATE",
    status: "FAILED",
    created_at: "2026-01-15T09:22:15Z",
  },
];

